# Generated by Django 4.1.7 on 2023-03-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('dateofbirth', models.CharField(max_length=20)),
                ('contact', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'register_table',
            },
        ),
    ]
